name: Java CI with Gradle

on:
  push:
    branches:
      - main  # Executa em push para o branch "main"
  pull_request:
    branches:
      - main  # Executa quando um PR é aberto ou atualizado para o branch "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4  # Baixa o código-fonte
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0  # Configura o Gradle

    # Gerar o APK com o Gradle
    - name: Build APK with Gradle
      run: ./gradlew assembleRelease  # ou assembleDebug, se necessário

    # Upload do APK como artefato
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/*.apk  # Caminho correto para o APK gerado
        
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4.0.0
